### ISSUE TITLE
Gcc version and cuda install

### ISSUE THREAD

**Issue by eliabntt** [heethesh/Computer-Vision-and-Deep-Learning-Setup#1]
Hi. When installing cuda with `sudo apt-get install -y cuda-8-0` I've met unmet dependencies solved by `sudo apt-get install ocl-icd-libopencl1`, I don't know if this is due to a minimal ubuntu 18.04 installation.

I've had problems also with `sudo apt-get install -y libjpeg8-dev libjasper-dev libpng12-dev` and 
`sudo apt-get install -y libqt4-dev libgtk2.0-dev libtbb-dev`, since they are not found in 18.04 but everything went right.

P.s. once you export the path for gcc/g++(w/o the .4) no need to add options in cmake either.

**Comment by heethesh** [comment]
Updated with support for CUDA 10 now
