### ISSUE TITLE
Error during opencv 3.4.0 make on ubuntu 18.04

### ISSUE THREAD

**Issue by shantanuctech** [heethesh/Computer-Vision-and-Deep-Learning-Setup#2]
Darknet for yolo only supports opencv <= 3.4.0
When installing opencv 3.4.0 using these instructions on ubuntu 18.04, i get n error during make. 

[ 12%] Linking CXX static library ../lib/liblibprotobuf.a
[ 12%] Built target libprotobuf
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Please suggest.

**Comment by heethesh** [comment]
`sudo apt install libopencv-dev` on Ubuntu 18 to install OpenCV 3.2 directly
